name: Build v11 - Release signed by Gradle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - uses: actions/checkout@v4

      - name: JDK 17 for SDK
        uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }

      - name: Android SDK 28
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          packages: 'platform-tools platforms;android-28 build-tools;28.0.3'

      - name: JDK 8 for Gradle
        uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '8' }

      - run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - run: chmod +x gradlew

      - name: Prepare buli keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 -d > $GITHUB_WORKSPACE/buli.jks

      - name: Build Release + ký luôn bằng Gradle
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew clean \
            :wallet:assembleProdRelease \
            :wallet:assembleTestRelease \
            :wallet:assembleSignetRelease \
            -x lint \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/buli.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Copy APKs
        run: |
          mkdir output
          cp wallet/build/outputs/apk/prod/release/wallet-prod-release.apk output/BitcoinWallet-prod-v11.apk
          cp wallet/build/outputs/apk/test/release/wallet-test-release.apk output/BitcoinWallet-test-v11.apk
          cp wallet/build/outputs/apk/signet/release/wallet-signet-release.apk output/BitcoinWallet-signet-v11.apk

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: v11-gradle-signed
          path: output/*.apk